accounts/urls.py
from django.conf.urls import patterns, url
from accounts.views import UpdateDescription, Detail

urlpatterns = patterns('accounts.views',
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^sign_in', 'sign_in', name='sign_in'),

    url(r'^detail/(?P<pk>\d+)/$', Detail.as_view(), name='detail'),

    url(r'^follow_unfollow/$', 'follow_unfollow', name='follow_unfollow'),
    url(r'^add_bookmark/$', 'add_bookmark', name='add_bookmark'),

    url(r'^(?P<pk>[\d]+)/(?P<who>followers|followings)/$', 'get_following_followers', name='get_following_followers'),

    url(r'^update_description/$', UpdateDescription.as_view(), name='update_description'),
)

thestorybay/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'thestorybay.views.index', name='index'),

    url(r'^accounts/', include(
        'accounts.urls',
        namespace='accounts',
        app_name='accounts')),

    url(r'^stories/', include(
        'stories.urls',
        namespace='stories',
        app_name='stories')),

    url(r'^comments/', include(
        'comments.urls',
        namespace='comments',
        app_name='comments')),

    url(r'^voting/', include(
        'voting.urls',
        namespace='voting',
        app_name='voting')),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^top$', 'thestorybay.views.top', name='top'),

    url(r'^admin/', include(admin.site.urls)),
)

voting/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('voting.views',
    url(r'^vote/(?P<object>story|comment)/(?P<pk>[\d]+)/$', 'vote', name='vote'),
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.urlresolvers import reverse
from settings.models import LikePower
from stories.models import Story
from sorl.thumbnail import ImageField as ThumbnailImageField


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None):
        if not username:
            raise ValueError('Users must have an username')
        user = self.model(
            password = password,
            username = username
        )
        user.email = email
        user.set_password(password)
        user.is_admin = False
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email=None, password=None):
        user = self.create_user(
            username = username,
            password = password
        )
        user.email = email
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(
        max_length = 50,
        unique = True,
        db_index = True)
    email = models.EmailField(blank=True, null=True)
    is_admin = models.BooleanField(default=False)
    rating = models.IntegerField(default=0)
    description = models.CharField(max_length=100, null=True, blank=True)
    link = models.CharField(max_length=255, null=True, blank=True)
    avatar = ThumbnailImageField(upload_to='upload/user_avatars/%Y/%m/%d')
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    bookmarks = models.ManyToManyField(Story, related_name='bookmark_users')
    objects = CustomUserManager()
    USERNAME_FIELD = 'username'

    @property
    def is_staff(self):
        return self.is_admin

    def get_short_name(self):
        return str(self.username)

    def get_full_name(self):
        return str(self.username)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def is_superuser(self):
        return False

    def __str__(self):
        return str(self.username)

    def get_absolute_url(self):
        return reverse('accounts:detail', kwargs={
            'pk':self.id})

accounts/forms.py
from django import forms
import re

from accounts.models import CustomUser


class EditDescription(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['description', 'link']
        widgets = {
            'description': forms.TextInput(attrs={'id': 'author_description'}),
            'link': forms.TextInput(attrs={'id': 'author_link'}),
        }

    def clean_link(self):
        link = self.cleaned_data.get('link', '')
        is_twitter = re.match('[http|https://][twitter.com/][a-zA-Z0-9_\-]+', link)
        is_facebook = re.match('[http|https://][facebook.com/][a-zA-Z0-9_\-]+', link)
        if not is_twitter and not is_facebook:
            raise forms.ValidationError('Wrong link.')
        return link

accounts/views.py
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout as django_logout
from django.template import RequestContext
from django.template.loader import render_to_string
from django.views.generic import UpdateView
from endless_pagination.views import AjaxListView

from accounts.forms import EditDescription
from accounts.models import CustomUser
from common.utils import AjaxForm
from stories.models import Story
from thestorybay.settings import BASE_REDIRECT


def logout(request):
    django_logout(request)
    return redirect(reverse(BASE_REDIRECT))


class Detail(AjaxListView):
    model = Story
    context_object_name = "stories"
    template_name = 'accounts/detail.html'
    page_template = 'stories/story_list_page.html'

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        author = get_object_or_404(CustomUser, pk=self.kwargs['pk'])
        if self.request.user == author:
            stories = Story.objects.filter( Q(bookmark_users=author) | Q(author=author) ).all()
        else:
            stories = Story.objects.filter( Q(bookmark_users=author) | Q(author=author, anonymous=False) ).all()
        context['stories'] = stories
        context['preview_template'] = 'stories/parts/preview.html'
        context['form_description'] = EditDescription(instance=author)
        context['author'] = author
        return context


class UpdateDescription(AjaxForm, UpdateView):
    model = CustomUser
    fields = ['description']
    form_class = EditDescription

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return self.object.get_absolute_url()


def sign_in(request):
    return render(request, 'accounts/modals/sign_in_modal.html')


def get_following_followers(request, pk, who):
    author = get_object_or_404(CustomUser, pk=pk)
    return render(request, 'accounts/modals/followings_followers.html', {
        'user': author,
        'who': who
    })


def add_bookmark(request):
    if request.is_ajax() and request.method == 'POST':
        story_pk = int(request.POST.get('story_pk'))
        story = get_object_or_404(Story, pk=story_pk)
        if request.user == story.author:
            return JsonResponse({
                'status': 'error',
                'message': "It's your story"
            })
        if request.user.bookmarks.filter(pk=story_pk).count() == 0:
            request.user.bookmarks.add(story)
            rendered_content = render_to_string('stories/widgets/add_in_bookmarks.html', RequestContext(request, {
                'story':story,
            }))
            return JsonResponse({
                'status': 'success',
                'message': 'Added to bookmarks',
                'rendered_content': rendered_content
            })
        else:
            return JsonResponse({
                'status': 'error',
                'message': 'Already in bookmarks'
            })
    return redirect(reverse(BASE_REDIRECT))


def follow_unfollow(request):
    if request.is_ajax() and request.method == 'POST':
        try:
            to_user_id = int(request.POST.get('author_pk'))
        except ValueError:
            return HttpResponse()
        from_user = request.user
        to_user = get_object_or_404(CustomUser, pk=to_user_id)
        if from_user.pk != to_user.pk:
            data = {
                'to': to_user.pk,
                'from': from_user.pk,
            }
            if  from_user.followings.filter(pk=to_user.pk).count() > 0:
                from_user.followings.remove(to_user)
                data['result'] = 'unfollow'
                data['message'] = 'You have unsubscribed from this author: {}'.format(to_user.username)
            else:
                from_user.followings.add(to_user)
                data['result'] = 'follow'
                data['message'] = 'You have subscribe to this author: {}'.format(to_user.username)
            data['status'] = 'success'
            rendered_content = render_to_string('accounts/widgets/follow_unfollow_form.html', RequestContext(request, {
                'author': to_user,
            }))
            data['rendered_content'] = rendered_content
            return JsonResponse(data)
    return redirect(reverse(BASE_REDIRECT))

accounts/templates/accounts/parts/detail.html
<div class="span-20 last prepend-top user_profile" data-pk="{{ author.pk }}">
      {% include 'accounts/parts/main_detail.html' %}

      <div class="span-2 prepend-top  colborder" align="center">
        <span class="current profile_num user_profile_rating">{{ author.rating }}</span>
        <br/>
        <a class="current follow_link" href="" title="">RATING</a>
      </div>
      <div class="span-2 prepend-top" align="center">
        <span class="current profile_num user_profile_followings">{{ author.followings.count }}</span>
        <br/>
        <a class="current follow_link show_modal" href="#" data-url="{% url 'accounts:get_following_followers' author.pk 'followings' %}" title="">FOLLOWING</a>
      </div>
      <div class="span-2 prepend-1 prepend-top last" align="center">
        <span id="author_detail_followers_count" class="current profile_num user_profile_followers">{{ author.followers.count }}</span>
        <br/>
        <a class="current follow_link show_modal" href="#" data-url="{% url 'accounts:get_following_followers' author.pk 'followers' %}"  title="">FOLLOWERS</a>
      </div>
</div>

accounts/templates/accounts/parts/main_detail.html
{% load thumbnail %}

<div class="span-3 avatar" align= "center">
  {% thumbnail author.avatar "140x140" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}
</div>

<div class="span-9 description_area">
  <h3>
    <a class="active_menu green_text_hover upper" href="{{ author.get_absolute_url }}" title="">- {{ author.username }}</a>
  </h3>
  <h4>
    <div class="self_info current">
      {% if request.user == author %}
        <form class="ajax_form" action="#" method="POST" data-url="{% url 'accounts:update_description' %}">
          {% csrf_token %}
          {{ form_description.description }}
          {{ form_description.link }}
        </form>
      {% else %}
        <div class="self_info current">{{ author.description }}</div>
        <a href="{{ author.link }}">{{ author.link }}</a>
      {% endif %}
    </div>
  </h4>
  <h3>
    {% include 'accounts/widgets/follow_unfollow_form.html' %}
  </h3>
</div>

accounts/templates/accounts/parts/top_preview.html
{% load thumbnail %}

<div class="span-9 last prepend-top" >
  <div class="span-2" align= "center">
    {% thumbnail author.avatar "80x80" crop="center" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
  </div>

  <div class="span-7">
    <h4 id="left_pad">
      <div>
        <a class="active_menu green_text_hover" href="{{ author.get_absolute_url }}" title="">- {{ author.username|upper }}</a>
        <br>
        <span class="self_info current">{{ author.description }}</span>
        <br>
        <span class="self_info current">
          {% if author.link %}
            <a href="{{ author.link }}">social profile</a>
          {% endif %}
        </span>
      </div>
      <div>
        {% include 'accounts/widgets/follow_unfollow_form.html' %}
      </div>
    </h4>
  </div>
</div>