comments/urls.py
from django.conf.urls import patterns, url
from comments.views import Create


urlpatterns = patterns('comments.views',
    url(r'^add/story/(?P<story_pk>[\d]+)/$',
        Create.as_view(),
        name='add'),
    )

thestorybay/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'thestorybay.views.index', name='index'),

    url(r'^accounts/', include(
        'accounts.urls',
        namespace='accounts',
        app_name='accounts')),

    url(r'^stories/', include(
        'stories.urls',
        namespace='stories',
        app_name='stories')),

    url(r'^comments/', include(
        'comments.urls',
        namespace='comments',
        app_name='comments')),

    url(r'^voting/', include(
        'voting.urls',
        namespace='voting',
        app_name='voting')),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^top$', 'thestorybay.views.top', name='top'),

    url(r'^admin/', include(admin.site.urls)),
)

voting/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('voting.views',
    url(r'^vote/(?P<object>story|comment)/(?P<pk>[\d]+)/$', 'vote', name='vote'),
)

comments/models.py
from django.db import models
from stories.models import Story
from thestorybay.settings import AUTH_USER_MODEL


class Comment(models.Model):
    author = models.ForeignKey(AUTH_USER_MODEL)
    story = models.ForeignKey(Story)
    to_comment = models.ForeignKey('self', blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    comment_text = models.TextField()
    rating = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_on']

comments/forms.py
from django import forms
from django.forms import ModelForm
import bleach
from django.conf import settings

from comments.models import Comment


class AddCommentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddCommentForm, self).__init__(*args, **kwargs)
        self.id = 'add_comment_form'

    class Meta:
        model = Comment
        fields = ('comment_text',)
        widgets={
            'comment_text':forms.Textarea(attrs={'id':'comment_text', 'class':'wysiwyg'}),
        }

    def clean_comment_text(self):
        comment_text = self.cleaned_data.get('comment_text', '')
        cleaned_text = bleach.clean(comment_text, settings.BLEACH_VALID_TAGS, settings.BLEACH_VALID_ATTRS)
        return cleaned_text


class AddCommentReplyForm(AddCommentForm):
    def __init__(self, *args, **kwargs):
        super(AddCommentForm, self).__init__(*args, **kwargs)
        self.id = 'add_comment_reply_form'

    class Meta(AddCommentForm.Meta):
        fields = ('comment_text', 'to_comment')
        widgets={
            'comment_text':forms.Textarea(attrs={'id':'comment_text_reply', 'class':'wysiwyg'}),
            'to_comment': forms.HiddenInput(attrs={'id': 'comment_pk'})
        }

comments/views.py
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.views.generic import CreateView

from common.utils import AjaxForm
from stories.models import Story
from comments.forms import AddCommentForm
from comments.models import Comment


class Create(AjaxForm, CreateView):
    model = Comment
    template_name = 'comments/add.html'
    form_class = AddCommentForm

    def dispatch(self, *args, **kwargs):
        self.story = get_object_or_404(Story, pk=kwargs['story_pk'])
        return super(Create, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return self.story.get_absolute_url()

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.story = self.story
        comment_pk = form.data.get('to_comment')
        if comment_pk: form.instance.to_comment = get_object_or_404(Comment, pk=comment_pk)
        branch_level = int(form.data.get('branch_level'))
        return super(Create, self).form_valid(form, **{
            'render_template': {
                'template':'comments/parts/detail.html',
                'context': {
                    'comment': form.instance,
                    'story': self.story,
                    'branch_level': branch_level,
                    'request': RequestContext(self.request)
                },
            },
            'status': 'success',
            'message': 'Your comment added'
        })

comments/templates/comments/add.html
<form id="{{ form.id }}" class="ajax_form" action="#" method="post"
      data-url="{{ form_action }}" data-after_event="after_comment" data-before_event="before_comment">
  {% csrf_token %}
  {{ form.comment_text }}
  {{ form.to_comment }}
  <div><input type="submit" value="Send" id="comment_reply__send_button"></div>
  {% if form.close_btn %}
  <a class="reply_comment_cancel" href="#" data-comment="{{ comment.pk }}" id="reply_comment_close">
    Close
  </a>
  {% endif %}
</form>

comments/templates/comments/block.html
{% if user.is_authenticated %}
  {% for form in forms %}
    {% include 'comments/add.html' %}
  {% endfor %}
{% endif %}

<div id="comment_block" class="ajax_paginate">
    {% include page_template %}
</div>

comments/templates/comments/branch.html
{% load math %}
{% load set %}

{% for comment in comments %}
  {% include 'comments/parts/detail.html' %}
  {% with comment.comment_set.all as comments %}
    {% math branch_level "($1 + 1)" as branch_level %}
    {% include 'comments/branch.html' %}
  {% endwith %}
{% endfor %}

comments/templates/comments/branch_page.html
{% load math %}
{% load set %}
{% load endless %}
{% paginate comments %}

{% if not branch_level %}
    {% set branch_level = 1 %}
{% endif %}

{% for comment in comments %}
  {% include 'comments/parts/detail.html' %}
  {% with comment.comment_set.all as comments %}
    {% math branch_level "($1 + 1)" as branch_level %}
    {% include 'comments/branch.html' %}
  {% endwith %}
{% endfor %}

{% show_more %}