stories/urls.py
from django.conf.urls import patterns, url
from stories.views import *


urlpatterns = patterns('stories.views',
    url(r'^library/$', Library.as_view(), name='library'),
    url(r'^library/by_tag/(?P<tag_slug>[\w-]+)/$', ByTag.as_view(), name='by_tag'),
    url(r'^hot/$', Hot.as_view(), name='hot'),
    url(r'^feed/$', Feed.as_view(), name='feed'),

    url(r'^detail/(?P<pk>[\d]+)/$', Detail.as_view(), name='detail'),
    url(r'^add/$', Create.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', Update.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', delete, name='delete'),

    url(r'^search_tags', search_tags, name='search_tags'),

    url(r'^search_form', 'search_form', name='search_form'),
    url(r'^search', Search.as_view(), name='search'),
)

thestorybay/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'thestorybay.views.index', name='index'),

    url(r'^accounts/', include(
        'accounts.urls',
        namespace='accounts',
        app_name='accounts')),

    url(r'^stories/', include(
        'stories.urls',
        namespace='stories',
        app_name='stories')),

    url(r'^comments/', include(
        'comments.urls',
        namespace='comments',
        app_name='comments')),

    url(r'^voting/', include(
        'voting.urls',
        namespace='voting',
        app_name='voting')),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^top$', 'thestorybay.views.top', name='top'),

    url(r'^admin/', include(admin.site.urls)),
)

voting/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('voting.views',
    url(r'^vote/(?P<object>story|comment)/(?P<pk>[\d]+)/$', 'vote', name='vote'),
)

stories/models.py
from math import log

from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from settings.models import LikePower
from django.utils import timezone
from thestorybay.settings import AUTH_USER_MODEL
from sorl.thumbnail import ImageField as ThumbnailImageField


class Tag(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    popular = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse(
            'stories:by_tag',
            args=[self.slug])

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name_plural = 'tags'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Tag, self).save(*args, **kwargs)


class Story(models.Model):
    title = models.CharField(max_length = 62)
    story_text = models.TextField()
    created_on = models.DateTimeField(auto_now_add = True)
    rating = models.IntegerField(default = 0)
    amount_views = models.IntegerField(default = 0)
    amount_comments = models.IntegerField(default = 0)
    cover = ThumbnailImageField(upload_to = 'upload/story_covers/%Y/%m/%d')
    author = models.ForeignKey(AUTH_USER_MODEL, related_name='written_stories')
    anonymous = models.BooleanField(default = False)
    tags = models.ManyToManyField(Tag, related_name='stories')

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = 'stories'

    def is_anonymous(self):
        return self.anonymous

    def get_absolute_url(self):
        return reverse('stories:detail', kwargs={
            'pk':self.id})

    def calc_hot_rating(self):
        EPOCH = timezone.make_aware(timezone.datetime(2014, 1, 1), timezone.utc)
        rating = \
            self.rating * 0.4 + \
            self.amount_views * 0.15 + \
            self.amount_comments * 0.5
        order = log(rating, 10)
        seconds = (self.created_on - EPOCH).total_seconds()
        self.hot_rating = order + seconds / 50000
        return self.hot_rating

    def __str__(self):
        r = str(self.title) + ' - '
        r += str(self.story_text)[:30] + ' - '
        r += str(self.author) + ' - '
        r += self.created_on.strftime('%d.%m.%Y - %H:%M') + ' - '
        r += 'views: ' + str(self.amount_views) + ' - '
        r += 'votes: ' + str(self.rating) + ' - '
        r += 'comments: ' + str(self.amount_comments)
        return r

    def get_username(self):
        if self.anonymous:
            return 'Anonymous'
        return self.author.username


class MetricStoryDetailViews(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL)
    story = models.ForeignKey(Story)
    date = models.DateTimeField(auto_now_add = True)

    def save(self, *args, **kwargs):
        if self.user != self.story.author:
            if not MetricStoryDetailViews.objects.filter(
                user=self.user, story=self.story):
                super(MetricStoryDetailViews, self).save(*args, **kwargs)
                return True
        return False

stories/forms.py
from django import forms
import bleach
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.utils.safestring import mark_safe

from stories.models import Story, Tag


class PopularTagsWidget(forms.CheckboxSelectMultiple):
    def render(self, name, value, attrs=None, choices=()):
        self.checked_popular_tags = self.checked_popular_tags or []
        output = []
        id = 'popular_tags_input_{}'
        i = 0
        for tag in self.choices.queryset:
            inp_id = id.format(i)
            checked = 'checked' if tag in self.checked_popular_tags else ''
            output.append('<div class="span-5 last checkbox_2 current">')
            output.append('<input type="checkbox" id="{}" value="{}" name="{}" {}>'
                          .format(inp_id, tag.pk, 'popular_tags', checked))
            output.append('<label for="{}" class="cursor_pointer">{}</label>'.format(inp_id, tag.title))
            output.append('<span class="green_text ">({} stories)</span>'.format(tag.num_stories))
            output.append('</div>')
            i += 1
        return mark_safe('\n'.join(output))


class EditStoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditStoryForm, self).__init__(*args, **kwargs)
        self.checked_popular_tags = []
        if self.instance.pk:
            self.checked_popular_tags = self.instance.tags.filter(popular=True)

        self.fields['popular_tags'] = forms.ModelMultipleChoiceField(
            required = False,
            queryset = Tag.objects.filter(popular=True).annotate(num_stories=Count('stories')),
            widget = PopularTagsWidget(),
        )
        self.fields['popular_tags'].widget.checked_popular_tags = self.checked_popular_tags

        self.fields['tags'] = forms.ModelMultipleChoiceField(
            required = False,
            queryset = Tag.objects.filter(popular=False),
            widget = forms.SelectMultiple(
                attrs = {
                    'data-placeholder':'Or search some category there...',
                    'data-url': reverse('stories:search_tags'),
                }
            )
        )

    class Meta:
        model = Story
        fields = ['title', 'story_text', 'cover', 'anonymous', 'tags']
        widgets={
            'title': forms.TextInput(attrs={'placeholder':'YOU STORY NAME','name':'title','class':'transparent_text2 green_placeholder'}),
            'story_text': forms.Textarea(attrs={'id':'story_textarea'}),
            'anonymous': forms.CheckboxInput(attrs={'id':'anonimous', 'placeholder':'YOU STORY NAME','name':'anonymous'}),
            'cover': forms.FileInput(attrs={'class': 'cursor_pointer'})
        }

    def clean_story_text(self):
        text = self.cleaned_data.get('story_text', '')
        cleaned_text = bleach.clean(text, settings.BLEACH_VALID_TAGS, settings.BLEACH_VALID_ATTRS)
        return cleaned_text

    def clean(self):
        cleaned_data = super(EditStoryForm, self).clean()
        if not cleaned_data.get('popular_tags') and not cleaned_data.get('tags'):
             raise forms.ValidationError({'tags': forms.ValidationError('Need to add tags', code='code')})
        return cleaned_data

    def save(self, commit=False, *args, **kwargs):
        self.cleaned_data['tags'] = list(self.cleaned_data['popular_tags']) + list(self.cleaned_data['tags'])
        return super(EditStoryForm, self).save(*args, **kwargs)

stories/views.py
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.templatetags.static import static
from django.views.generic import CreateView, UpdateView
from endless_pagination.views import AjaxListView

from comments.models import Comment
from common.utils import AjaxForm, JsonView
from stories.models import Story, MetricStoryDetailViews, Tag
from stories.forms import EditStoryForm
from comments.forms import AddCommentForm, AddCommentReplyForm
from thestorybay.settings import BASE_REDIRECT


class Library(AjaxListView):
    model = Story
    context_object_name = "stories"
    template_name = 'stories/story_list.html'
    page_template = 'stories/story_list_page.html'

    def get_context_data(self, **kwargs):
        context = super(Library, self).get_context_data(**kwargs)
        context['preview_template'] = 'stories/parts/preview.html'
        return context


class Hot(Library):
    def get_queryset(self):
        return sorted(Story.objects.filter(rating__gt=0), key = lambda story: -story.calc_hot_rating())


class ByTag(Library):
    def get_queryset(self):
        tag = get_object_or_404(Tag, slug=self.kwargs['tag_slug'])
        return Story.objects.filter(tags=tag)


class Feed(Library):
    def get_queryset(self):
        followings = self.request.user.followings.all()
        stories = Story.objects.filter(
            Q(bookmark_users=followings) |
            Q(author=followings, anonymous=False) |
            Q(votes=followings)
        ).distinct()
        for story in stories:
            vote_users = [vote.user for vote in story.votes.all()]
            bookmark_users = story.bookmark_users.all()
            story.my_following_bookmark_users = list(set(followings).intersection(set(bookmark_users)))
            story.my_following_vote_users = list(set(followings).intersection(set(vote_users)))
        return stories


class Search(JsonView, Library):
    context_to_json = ['count_stories']

    def get_context_data(self, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        context['count_stories'] = len(context['object_list'])
        context['preview_template'] = 'stories/parts/preview.html'
        return context

    def get_queryset(self):
        return Story.objects.filter(title__icontains=self.request.GET['q'])


def search_form(request):
    return render(request, 'stories/modals/search_modal.html', {
        'additional_scripts': [static('js/initSearch.js')]
    })


class Detail(AjaxListView):
    model = Comment
    context_object_name = "comments"
    template_name = 'stories/story_detail.html'
    page_template = 'comments/branch_page.html'

    def get_queryset(self):
        return self.story.comment_set.filter(to_comment=None)

    def dispatch(self, *args, **kwargs):
        self.story = get_object_or_404(Story, pk=kwargs['pk'])
        MetricStoryDetailViews.objects.get_or_create(user = self.request.user, story = self.story)
        return super(Detail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['additional_scripts'] = [
            static('js/initDetailStory.js'),
            static('js/sdk.js')
        ]
        context['form_action'] = reverse('comments:add', kwargs={'story_pk': self.story.pk})
        reply_form = AddCommentReplyForm()
        reply_form.close_btn = True
        context['forms'] = [AddCommentForm(), reply_form]
        context['story'] = get_object_or_404(Story, pk=self.kwargs.get('pk'))
        return context


class Create(AjaxForm, CreateView):
    model = Story
    fields = ['title', 'text', 'cover', 'anonymous', 'category']
    template_name = 'stories/modals/edit.html'
    form_class = EditStoryForm

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(Create, self).get_context_data(**kwargs)
        context['additional_scripts'] = [
            static('select2/js/select2.min.js'),
            static('js/initEditStoryForm.js')
        ]
        context['additional_css'] = [
            static('select2/css/select2.min.css'),
        ]
        context['form_action'] = reverse('stories:add')
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(Create, self).form_valid(form)


class Update(Create, UpdateView):
    def get_context_data(self, **kwargs):
        context = super(Update, self).get_context_data(**kwargs)
        context['form_action'] = reverse('stories:edit', kwargs={'pk':self.get_object().id})
        context['form_delete'] = reverse('stories:delete', kwargs={'pk':self.get_object().id})
        return context


def delete(request, pk):
    story = get_object_or_404(Story, pk=pk)
    redirect_url = story.author.get_absolute_url()
    if story.author == request.user:
        story.delete()
    if request.is_ajax():
        return JsonResponse({'redirect_url': redirect_url})
    return redirect(redirect_url)


def search_tags(request):
    if request.is_ajax():
        tags = Tag.objects.filter(
             Q(title__icontains=request.GET['q']) &
             Q(popular=False)
        )
        data = {}
        data['items'] = [{'id': tag.pk, 'title': tag.title } for tag in tags]
        return JsonResponse(data)
    return redirect(reverse(BASE_REDIRECT))

stories/templates/stories/modals/edit.html
{% extends 'modals/base_modal.html' %}
{% block modal_content %}
      <div class="prepend-3 span-18 last">
        <form class="ajax_form" name="edit_story_form" method="post" action="#" enctype="multipart/form-data"
          data-url="{{ form_action }}" data-before_event="before_edit_story" data-after_event="after_edit_story">
            {% csrf_token %}
    {# add1 #}
          <div id='mod_add_story_form_content1'>
            <div class="span-14 last">
              <p id='err_title' class='error_labeles'></p>
            </div>
            <div class="span-14 last">
              <label for="id_title" class="label" ></label>
              {{ form.title }}
            </div>

            <div class="span-3 last checkbox prepend-top current right">
              {{ form.anonymous }}<label for="anonimous" class="cursor_pointer">Anonimous story?</label>
            </div>

            <div class="span-18 last">
              <p id='err_story_text' class='error_labeles'></p>
            </div>
            <div class="span-18 last">
              <label for="id_story_text" class="label"></label>
              {{ form.story_text }}
            </div>
            <div class="span-18 last">
              <p id='err_cover' class='error_labeles'></p>
            </div>

            <div class="span-18 last container_upload upload">
              <label for="id_cover" class="label"></label>
              <span class="btn story_cover_btn" id="story_cover_btn">CHOOSE YOU STORY COVER<span id="button_clip" ></span></span>
              {{ form.cover }}
            </div>

            <div class="span-7">
              <button id="edit_story_form_next" class="green_button cursor_pointer" type="button"><span class="white_text">NEXT</span></button>
            </div>

            {% if form.instance.pk %}
              <div class="prepend-2 span-8 right">
                <button onsubmit="return checkForm(this)" id="edit_story_form_delete" class="red_button cursor_pointer" type="button" data-delete_url="{{ form_delete }}">
                  <span class="white_text">DELETE THIS STORY</span>
                </button>
              </div>

            {% endif %}
          </div>
    {# add2 #}
          <div id='mod_add_story_form_content2'>
            <div class="span-14 last">
              <p id='err_tags' class='error_labeles'></p>
            </div>
              <div class="span-9 last prepend-top">
                <h4 class="transparent_text green_text" id="tags_header"> CHOOSE CATEGORY OF YOU STORY </h4>
              </div>

              <div class="span-12 last">
                {{ form.popular_tags }}
              </div>

              <div id="edit_story_input_tags_block" class="side-by-side clearfix span-16 last">
                <em><label for="multiple-label-example"></label></em>
                {{ form.tags }}
              </div>
              <button class="green_button cursor_pointer" type="submit"><span class="white_text">PUBLISH THIS STORY</span></button>
            </div>
        </form>
      </div>
  {{ form.media }}
{% endblock %}

stories/templates/stories/modals/search_modal.html
{% extends 'modals/base_modal.html' %}
{% block modal_content %}
    <div class="prepend-3 span-18 last">
      <form class="ajax_form" name="search_form" method="get" action="#"
            data-url="{% url 'stories:search' %}" data-before_event="before_search" data-after_event="after_search">
        <div class="span-14 green_text">
          <input type="text" name="q" class="green_text" size="60" id="search_request" placeholder=" Type to search...">
        </div>
      </form>
    </div>
    <div id="found_info">
      <div class="span-19 last prepend-3">
        <h3 class="green_text">
          <span id="story_count"></span>
          <span class="current">STORIES</span>
        </h3>
      </div>
    </div>
    <div id="found_block"></div>
{% endblock %}