accounts/urls.py
from django.conf.urls import patterns, url
from accounts.views import UpdateDescription, Detail

urlpatterns = patterns('accounts.views',
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^sign_in', 'sign_in', name='sign_in'),

    url(r'^detail/(?P<pk>\d+)/$', Detail.as_view(), name='detail'),

    url(r'^follow_unfollow/$', 'follow_unfollow', name='follow_unfollow'),
    url(r'^add_bookmark/$', 'add_bookmark', name='add_bookmark'),

    url(r'^(?P<pk>[\d]+)/(?P<who>followers|followings)/$', 'get_following_followers', name='get_following_followers'),

    url(r'^update_description/$', UpdateDescription.as_view(), name='update_description'),
)

stories/urls.py
from django.conf.urls import patterns, url
from stories.views import *


urlpatterns = patterns('stories.views',
    url(r'^library/$', Library.as_view(), name='library'),
    url(r'^library/by_tag/(?P<tag_slug>[\w-]+)/$', ByTag.as_view(), name='by_tag'),
    url(r'^hot/$', Hot.as_view(), name='hot'),
    url(r'^feed/$', Feed.as_view(), name='feed'),

    url(r'^detail/(?P<pk>[\d]+)/$', Detail.as_view(), name='detail'),
    url(r'^add/$', Create.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', Update.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', delete, name='delete'),

    url(r'^search_tags', search_tags, name='search_tags'),

    url(r'^search_form', 'search_form', name='search_form'),
    url(r'^search', Search.as_view(), name='search'),
)

thestorybay/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'thestorybay.views.index', name='index'),

    url(r'^accounts/', include(
        'accounts.urls',
        namespace='accounts',
        app_name='accounts')),

    url(r'^stories/', include(
        'stories.urls',
        namespace='stories',
        app_name='stories')),

    url(r'^comments/', include(
        'comments.urls',
        namespace='comments',
        app_name='comments')),

    url(r'^voting/', include(
        'voting.urls',
        namespace='voting',
        app_name='voting')),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^top$', 'thestorybay.views.top', name='top'),

    url(r'^admin/', include(admin.site.urls)),
)

voting/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('voting.views',
    url(r'^vote/(?P<object>story|comment)/(?P<pk>[\d]+)/$', 'vote', name='vote'),
)

templates/aside.html
{% url 'stories:hot' as stories_hot_url %}
{% url 'stories:library' as stories_library_url %}
{% url 'top' as top_url %}
{% url 'stories:feed' as stories_feed_url %}

{% if request.get_full_path == stories_hot_url %}
  <h3><a class="active_menu" href="{{ stories_hot_url }}">HOT</a></h3>
{% else %}
  <h3><a class="current" href="{{ stories_hot_url }}">HOT</a></h3>
{% endif %}
{% if request.get_full_path == top_url  %}
  <h3> <a class="active_menu" href="{{ top_url }}">TOP</a></h3>
{% else %}
    <h3> <a class="current" href="{{ top_url }}">TOP</a></h3>
{% endif %}
{% if request.get_full_path == stories_library_url %}
  <h3><a class="active_menu" href="{{ stories_library_url }}">LIBRARY</a></h3>
{% else %}
  <h3><a class="current" href="{{ stories_library_url }}">LIBRARY</a></h3>
{% endif %}
{% if user.is_authenticated %}
  {% if request.get_full_path == stories_feed_url %}
    <h3><a class="active_menu" href="{{ stories_feed_url }}">FEED</a></h3>
  {% else %}
    <h3><a class="current" href="{{ stories_feed_url }}">FEED</a></h3>
  {% endif %}
{% endif %}

{% if story.get_absolute_url %}
  <div class="fullstory_stat story_info" data-pk="{{ story.pk }}">
    <h4>THIS STORY</h4>
    <hr />
    <table>
    <tr>
      <td class="row-1">Views</td>
      <td class="green_text row-2 story_amount_views">{{ story.amount_views }}</td>
    </tr>
    <tr>
      <td class="row-1">Rating</td>
      <td class="green_text row-2 story_rating">{{ story.rating }}</td>
    </tr>
    <tr>
      <td class="row-1">Comments</td>
      <td class="green_text row-2 story_amount_comments">{{ story.amount_comments }}</td>
    </tr>
    </table>
  </div>
  {% if not story.anonymous %}
    <div class="fullstory_stat user_profile" data-pk="{{ story.author.pk }}">
      {% if user != story.author and story.is_anonymous %}
        <span class="post_auth_name upper">Anonymous</span>
      {% else %}
        <a class="post_auth_name upper" href="{{ story.author.get_absolute_url }}">- {{ story.author }}</a>
      {% endif %}
      <hr/>
      <table>
        <tr>
          <td class="row-1">Stories</td>
          <td class="green_text row-2 user_profile_stories_count">{{ story.author.written_stories.count }}</td>
        </tr>
        <tr>
          <td class="row-1">Readers</td>
          <td class="green_text row-2 user_profile_followers">{{ story.author.followers.count }}</td>
        </tr>
        <tr>
          <td class="row-1">Rating</td>
          <td class="green_text row-2 user_profile_rating">{{ story.author.rating }}</td>
        </tr>
      </table>
    </div>
  {% endif %}
{% endif %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>thestorybay || {% block title %}{% endblock %}</title>

  {% compress css %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/blueprint/screen.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/arcticmodal.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.growl.css' %}" />
      {% if additional_css %}
          {% for css in additional_css %}
              <link rel="stylesheet" type="text/css" href="{{ css }}" />
          {% endfor %}
      {% endif %}
  {% endcompress %}

  <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
  {% compress js %}
      <script src="{% static 'js/jquery.js' %}"></script>
      <script src="{% static 'js/arcticmodal.js' %}"></script>
      <script src="{% static 'endless_pagination/js/endless-pagination.js' %}"></script>
      <script src="{% static 'endless_pagination/js/endless_on_scroll.js' %}"></script>
      <script src="{% static 'ckeditor/adapters/jquery.js' %}"></script>
      <script src="{% static 'js/jquery.growl.js' %}"></script>
      <script src="{% static 'js/tools.js' %}"></script>
      <script src="{% static 'js/ajax_form.js' %}"></script>
      <script src="{% static 'js/ajax_form_events.js' %}"></script>
      <script src="{% static 'js/js.js' %}"></script>
      <script src="{% static 'js/jquery.animate-colors-min.js' %}"></script>
      {% if additional_scripts %}
        {% for script_name in additional_scripts %}
          <script src="{{ script_name }}"></script>
        {% endfor %}
      {% endif %}
  {% endcompress %}
</head>

<body>
  <div class="container">
    {% include 'header.html' %}

    <div class="span-4 prepend-top">
      {% include 'aside.html' %}
    </div>

    <div class="span-20 last">
       {% block content %}{% endblock %}
    </div>
  </div>
</body>

templates/header.html
<div class="heading container">
  <div class="column span-4 prepend-top">
    <h3><a class="active_menu green_text_hover" href="{% url 'index' %}" title="">thestorybay.com</a></h3>
  </div>

  <div class="column span-6 prepend-top">
    <div>
      <h3>
        <a class="active_menu green_text_hover show_modal" href="#" data-url="{% url 'stories:search_form' %}">
          <span class="search-icon-hi"></span>
          <span class="search_text">search</span>
        </a>
      </h3>
    </div>
  </div>

  {% if user.is_authenticated %}
    <div class="column span-13 prepend-top user-block">
      <h3>
        <a id="mod_add_story" class="active_menu green_text_hover show_modal" href="#" data-url="{% url 'stories:add' %}">WRITE YOU STORY,</a>
        <a class="active_menu green_text_hover upper" href="{{ user.get_absolute_url }}"><b>- {{ user }}</b></a>
      </h3>
      <div>
        <a class="right logout current" href="{% url 'accounts:logout' %}">logout</a>
      </div>
    </div>
    <div class="column span-1 last" align="right">
      <a href="{{ user.get_absolute_url }}"><p class="star_ico"></p></a>
    </div>
  {% else %}
    <div class="column span-13 header_login prepend-top user-block">
      <h3>
        <a class="active_menu green_text_hover show_modal" href="#" data-url="{% url 'accounts:sign_in' %}">BECOME A WRITESTAR</a>
      </h3>
    </div>
    <div class="column span-1 last">
      <a class="right show_modal" href="#" data-url="{% url 'accounts:sign_in' %}"><p class="star_ico"></p></a>
    </div>
  {% endif %}
</div>